#action_tests.yml
name: Run Playwright Test In Main Brnch Using Docker Action
description: Run Playwright Test In Main Brnch Using Docker Action
branding:
  icon: 'git-branch'
  color: green
inputs:
  owner:
    description: 'alexfariakof'
    required: true
  repo:
    description: 'despesas-frontend-angular-tests-e2e'
    required: true
runs:
  using: 'composite'  
  steps:
    - name: Run Tests with Playwright      
      shell: bash 
      run: |
        docker-compose -f docker-compose.tests.e2e.yml up
