#action.yml
name: List Branches Docker Action
description: Lista branches de um repositório público
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  owner: alexfariakof
    description: 'alexfariakof'
    required: true
  repo: despesas-frontend-angular
    description: 'despesas-frontend-angular'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repo }} 