name: Execute Workflow Tests E2E
on:
  repository_dispatch:
    types: [trigger-python-plyawright-e2e-tests]

jobs:
  Triggered-Tests-E2E:
    runs-on: ubuntu-latest  
    outputs:
      run_id: ${{ steps.get_run_id.outputs.run_id }}
    steps:                  
      - name: Get Workflow ID
        id: get_run_id
        run: |
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT

  Run-Tests-E2E:
    needs: Triggered-Tests-E2E
    name : Running in ${{ matrix.browser }}
    strategy:
      matrix:
        #browser: [firefox, chrome, webkit]
        browser: [firefox]
    runs-on: ubuntu-latest  
    steps:          
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"    
  
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright
          playwright install
          playwright install-deps   
          
      - name: Runnig Tests e2e With Playwright
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            pytest --browser firefox
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            pytest --browser chromium
          else
            pytest
          fi

  Response-Triggered-Tests-E2E:
    needs: Run-Tests-E2E
    name : Response Triggered Tests E2E
    runs-on: ubuntu-latest  
    outputs:
      workflow_status: ${{ steps.response_tests_e2e.outputs.workflow_status }}  
    steps:
      - uses: actions/checkout@v3      
      - name: Set Workflow Status
        id: response_tests_e2e
        run: |
          echo "workflow_status=${{ job.status }}" >> $GITHUB_OUTPUT