name: Execute Workflow Tests E2E
on:
  repository_dispatch:
    types: [trigger-python-plyawright-e2e-tests]

jobs:
  Triggered-Tests-E2E:
    name : Triggered Tests E2E
    outputs:
      run_id: ${{ steps.get_run_id.outputs.run_id }}
      workflow_status: ${{ steps.run_tests_e2e.outputs.workflow_status }}
    strategy:
      matrix:
        browser: [firefox, chrome, webkit]
    runs-on: ubuntu-latest
    steps:          
      - name: Get Workflow Run ID
        id: Starting_e2e_Test_Execution
        run: |
          run_id=$(echo "${{ github.event.client_payload.workflow_run_id }}" | awk -F/ '{print $NF}')
          echo "Workflow Run ID: $run_id"
          echo "::set-output name=run_id::$run_id"
  
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"    
  
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright
          playwright install
          playwright install-deps   
          
      - name: Runnig Tests e2e With Playwright
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            pytest --browser firefox
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            pytest --browser chromium
          else
            pytest
          fi
      - name: Set Workflow Status
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Workflow Status: success"
            echo "::set-output name=workflow_status::success"
          else
            echo "Workflow Status: failure"
            echo "::set-output name=workflow_status::failure"