name: Execute Workflow Tests E2E
on:
  repository_dispatch:
    types: [trigger-python-plyawright-e2e-tests]

jobs:
  Triggered-Tests-E2E:
    name : Running Tests e2e in ${{ matrix.browser }}
    outputs:
      run_id: ${{ steps.get_run_id.outputs.run_id }}
    strategy:
      matrix:
        browser: [firefox, chrome, webkit]
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3
      - name: Get Workflow Run ID      
        id: get_run_id
        run: |
          echo "Workflow Run ID: "
          echo "run_id=${{ github.event.client_payload.workflow_run_id }}" >> $GITHUB_ENV
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"    
  
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright
          playwright install
          playwright install-deps   
          
      - name: Runnig Tests e2e With Playwright
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            pytest --browser firefox
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            pytest --browser chromium
          else
            pytest
          fi

  Response-Triggered-Tests-E2E:
    needs: Triggered-Tests-E2E
    name : Response Triggered Tests E2E
    outputs:
      workflow_status: ${{ steps.response_tests_e2e.outputs.workflow_status }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Workflow Status
        id: response_tests_e2e
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Workflow Status: success"
            echo "{workflow_status=success" >> $GITHUB_ENV
          else
            echo "Workflow Status: failure"
            echo "{workflow_status}={failure}" >> $GITHUB_ENV