name: Execute Workflow Tests E2E
on:
  repository_dispatch:
    types: [trigger-python-plyawright-e2e-tests]

jobs:
  dispatch:
    strategy:
      matrix:
        browser: [firefox, chrome, webkit]
    runs-on: ubuntu-latest
    if: github.event.client_payload.event-type == 'trigger-python-plyawright-e2e-tests'
    steps:          
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"    
  
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright
          playwright install
          playwright install-deps   
          
      - name: Test e2e with playwright
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            pytest --browser firefox
          elif [ "${{ matrix.browser }}" == "chrome" ]; then
            pytest --browser chromium
          else
            pytest
          fi