on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        browser: [firefox, chrome, ie, webkit, safari, edge]
    runs-on: ubuntu-latest
    steps:
          
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libvpx-dev \
          libsoup2.4-dev \
          libevent-2.1-6 \
          libopus-dev \
          libharfbuzz-icu0 \
          libgstreamer-plugins-base1.0-0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-good1.0-0 \
          libgstreamer-plugins-bad1.0-0 \
          libgstreamer-gl1.0-0 \
          libgstreamer-plugins-bad1.0-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libgles2 \
          libx264-160
          
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright
        playwright install
  
    - name: Test e2e with playwright
      run: |
        if [ "${{ matrix.browser }}" == "firefox" ]; then
          pytest --browser firefox
        elif [ "${{ matrix.browser }}" == "chrome" ]; then
          pytest --browser chromium
        elif [ "${{ matrix.browser }}" == "ie" ]; then
          pytest --browser webkit
        elif [ "${{ matrix.browser }}" == "safari" ]; then
          pytest --browser safari
        elif [ "${{ matrix.browser }}" == "edge" ]; then
          pytest --browser webkit
        else
          echo "Unsupported browser: ${{ matrix.browser }}"
        fi