on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        browser: [firefox, chrome, ie, webkit, safari, edge]
    runs-on: ubuntu-latest
    steps:
          
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright
        playwright install
        playwright install-deps   
        
    - name: Test e2e with playwright
      run: |
        if [ "${{ matrix.browser }}" == "firefox" ]; then
          pytest --browser firefox
        elif [ "${{ matrix.browser }}" == "chrome" ]; then
          pytest --browser chromium
        elif [ "${{ matrix.browser }}" == "ie" ]; then
          pytest --browser webkit
        elif [ "${{ matrix.browser }}" == "safari" ]; then
          pytest --browser safari
        elif [ "${{ matrix.browser }}" == "edge" ]; then
          pytest --browser webkit
        else
          pytest
        fi