on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    
jobs:
  List-Branches:
    runs-on: ubuntu-latest
    name: Job Run Playwright Tests
    
    steps:
      
      - name: Run Playwright Tests        
        id: tests
        uses: alexfariakof/despesas-frontend-angular-tests-e2e@main        
        with:
          owner: 'alexfariakof'
          repo: 'despesas-frontend-angular-tests-e2e'        
          
