on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
      
    - name: Cache Python Dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/__pycache__
        key: ${{ runner.os }}-python-${{ hashFiles('**/*.lock') }}
        restore-keys: ${{ runner.os }}-python-
  
    - name: Create if not Exist Cache Packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/__pycache__
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright
        playwright install
  
    - name: Test e2e with playwright
      run: pytest